"""The published site is a build artifact, so it is tested like one.

The site is generated by ``scripts/build_site_ds48.py`` from ``registry/`` and
``evidence/``, which means every number on it is machine-derived.  These tests
check the properties that page generation can actually get wrong: a page that
did not get written, a download link that does not resolve, a placeholder that
survived into the HTML, a stylesheet that went missing, and -- the one that
matters most for this project -- an out-of-date range quoted next to a file.
"""
from __future__ import annotations

import json
import re
import unittest
from html.parser import HTMLParser

import conftest  # noqa: F401  (path bootstrap)

#: This session's site.  It publishes into its own directory so that the other
#: sessions' pages under docs/ are never overwritten; see the note in
#: scripts/build_site_ds48.py.
SUB = conftest.DOCS / "ds48-fusion"
PAGES = [
    "index.html",
    "executive-summary.html",
    "research.html",
    "hypotheses.html",
    "sources.html",
    "irregularities.html",
]
#: The repository landing page, built by another session's scripts/build_site.py.
FOREIGN_PAGES = ["index.html", "executive-summary.html", "hypotheses.html",
                 "irregularities.html", "method.html", "leaderboard.html"]
VOID = {"area", "base", "br", "col", "embed", "hr", "img", "input", "link",
        "meta", "param", "source", "track", "wbr"}


class _Nesting(HTMLParser):
    def __init__(self):
        super().__init__()
        self.stack: list[tuple[str, tuple[int, int]]] = []
        self.errors: list[str] = []

    def handle_starttag(self, tag, attrs):
        if tag not in VOID:
            self.stack.append((tag, self.getpos()))

    def handle_endtag(self, tag):
        if tag in VOID:
            return
        if not self.stack:
            self.errors.append(f"stray </{tag}> at {self.getpos()}")
            return
        if self.stack[-1][0] != tag:
            self.errors.append(
                f"</{tag}> at {self.getpos()} closes <{self.stack[-1][0]}> "
                f"opened at {self.stack[-1][1]}"
            )
            self.stack.pop()
        else:
            self.stack.pop()


class TestPagesExistAndAreWellFormed(unittest.TestCase):
    def test_all_six_pages_written(self):
        for name in PAGES:
            with self.subTest(page=name):
                p = SUB / name
                self.assertTrue(p.exists(), f"missing page {name}")
                self.assertGreater(p.stat().st_size, 2000, f"{name} looks empty")

    def test_nojekyll_marker_present(self):
        """GitHub Pages must not run Jekyll over the downloads directory."""
        self.assertTrue((conftest.DOCS / ".nojekyll").exists())
        self.assertTrue((SUB / ".nojekyll").exists())

    def test_stylesheet_present(self):
        css = conftest.DOCS / "assets" / "ds48-fusion" / "site.css"
        self.assertTrue(css.exists(), "docs/assets/ds48-fusion/site.css missing")
        self.assertGreater(css.stat().st_size, 1000)

    def test_the_other_sessions_pages_are_still_published(self):
        """This branch must not have clobbered the repository landing page."""
        for name in FOREIGN_PAGES:
            with self.subTest(page=name):
                self.assertTrue((conftest.DOCS / name).exists(),
                                f"docs/{name} was removed by this branch")

    def test_html_nesting_is_balanced(self):
        for name in PAGES:
            with self.subTest(page=name):
                parser = _Nesting()
                parser.feed((SUB / name).read_text())
                self.assertEqual(parser.errors, [])
                self.assertEqual([t for t, _ in parser.stack], [])

    def test_no_unresolved_placeholders(self):
        """A format string that survived into the output is a build failure."""
        for name in PAGES:
            with self.subTest(page=name):
                text = (SUB / name).read_text()
                for bad in ("None", "nan", "TODO", "XXX", "{esc(", "{fmt("):
                    self.assertNotIn(bad, text, f"{name} contains {bad!r}")

    #: Numbers that are properties of the Dempster-Shafer construction rather
    #: than scores: Bel at full agreement, Bel with one silent family, m(Theta)
    #: at zero and full conflict, K's maximum, and the (0.5, 0.5) worked value.
    DS_THEORY_VALUES = {"0.8400", "0.3750", "0.2500", "0.1600", "0.3600", "0.4024", "0.1800"}

    @staticmethod
    def _body(text: str) -> str:
        """The page body, without the header/nav/title chrome.

        The navigation label "Why 0.2778 won" contains a score-shaped number and
        is not a claim about a file, so it is excluded rather than special-cased.
        """
        i = text.find("<main")
        return text[i:] if i >= 0 else text

    def test_scores_are_labelled_and_theory_values_are_not_mistaken_for_scores(self):
        """No page may float a leaderboard-shaped number without its context.

        The risk this guards is a local proxy being written in the shape of a
        leaderboard score.  Numbers in the leaderboard band (0.30-0.33) must sit
        next to the word "leaderboard" or a named competitor; numbers that are
        properties of Dempster-Shafer theory are exempt and are listed explicitly.
        """
        for name in PAGES:
            with self.subTest(page=name):
                text = self._body((SUB / name).read_text())
                for m in re.finditer(r"0\.(?:2[5-9]|3[0-3])\d{2}", text):
                    value = m.group(0)
                    if value in self.DS_THEORY_VALUES:
                        continue
                    window = text[max(0, m.start() - 500): m.end() + 500]
                    self.assertTrue(
                        any(k in window for k in ("leaderboard", "DARD", "nchuzhoy",
                                                  "kinghorton42", "0.3195", "0.3262",
                                                  "OWNER-REPORT", "owner-reported",
                                                  "live", "Live", "LIVE")),
                        f"{name}: {value} quoted without a leaderboard source or "
                        f"an owner-report label",
                    )

    def test_every_page_states_that_nothing_here_is_organizer_scored(self):
        """Each page of this sub-site must carry its own unscored disclaimer.

        The footer is emitted on every page by scripts/build_site_ds48.py, so this
        is a check on the generator, not on five hand-written strings.
        """
        for name in PAGES:
            with self.subTest(page=name):
                text = (SUB / name).read_text()
                self.assertIn("No organizer score exists", text)
                self.assertIn("UNSCORED", (SUB / "index.html").read_text())


class TestLinksAndDownloads(unittest.TestCase):
    def test_every_local_href_resolves(self):
        for name in PAGES:
            page = SUB / name
            text = page.read_text()
            for href in re.findall(r'href="([^"#]+)"', text):
                if href.startswith(("http://", "https://", "mailto:")):
                    continue
                with self.subTest(page=name, href=href):
                    self.assertTrue(
                        (SUB / href).resolve().exists(),
                        f"{name}: broken local link {href}",
                    )

    MINE = [
        "gemsdoe48-ds48-belief.tif",
        "gemsdoe48-ds48-conflict.tif",
        "gemsdoe48-ds48-emission.tif",
        "gemsdoe48-ds48-mtheta.tif",
    ]

    def test_every_download_is_reachable_and_non_trivial(self):
        """This branch adds four files; it must not remove anyone else's."""
        d = conftest.DOWNLOADS
        present = {p.name for p in d.glob("*.tif")}
        for name in self.MINE:
            with self.subTest(file=name):
                self.assertIn(name, present)
                self.assertGreater((d / name).stat().st_size, 100_000)
        # other sessions' downloads are still there
        self.assertGreater(len(present - set(self.MINE)), 5)

    def test_the_index_links_the_emission_directly_at_the_top(self):
        """The brief: the download must be obvious at the very top of the page."""
        text = (SUB / "index.html").read_text()
        first = text.find("downloads/gemsdoe48-ds48-emission.tif")
        self.assertGreater(first, 0, "the emission is not linked from the sub-site index")
        # within the first third of the document, and with a download attribute
        self.assertLess(first, len(text) / 3)
        link = text[max(0, first - 400): first + 120]
        self.assertIn("download", link)

    def test_external_sources_are_linked_with_full_urls(self):
        text = (conftest.DOCS / "sources.html").read_text()
        urls = re.findall(r'href="(https?://[^"]+)"', text)
        self.assertGreaterEqual(len(urls), 10, "too few official sources linked")
        for u in urls:
            self.assertRegex(u, r"^https?://[a-z0-9.-]+\.[a-z]{2,}/", u)
        self.assertTrue(any("sciencebase.gov" in u or "usgs.gov" in u for u in urls))
        self.assertTrue(any("drivendata" in u for u in urls))


class TestSiteAgreesWithTheReceipts(unittest.TestCase):
    """A page that quotes a stale number is worse than a page with no number."""

    def setUp(self):
        self.rec = json.loads((conftest.REGISTRY / "submission_build.json").read_text())
        self.index = (SUB / "index.html").read_text()
        self.exec_sum = (SUB / "executive-summary.html").read_text()

    def test_unique_name_appears_on_the_site(self):
        for name, text in (("index", self.index), ("exec", self.exec_sum)):
            with self.subTest(page=name):
                self.assertIn(self.rec["unique_name"], text)

    def test_emission_mass_matches_the_receipt(self):
        n = self.rec["format_checks"]["emission"]["n_positive"]
        self.assertIn(f"{n:,}", self.index)

    def test_quoted_ranges_match_the_bytes(self):
        """Every '[lo, hi]' range on the executive summary must be a real range."""
        import rasterio

        ranges = re.findall(r"\[(\d\.\d{4}), (\d\.\d{4})\]", self.exec_sum)
        self.assertGreaterEqual(len(ranges), 4)
        real = set()
        for tag in ("belief", "emission", "mtheta", "conflict"):
            meta = self.rec["files"][tag]
            with rasterio.open(conftest.DOWNLOADS / meta["file"]) as src:
                a = src.read(1)
            real.add((f"{float(a.min()):.4f}", f"{float(a.max()):.4f}"))
        for lo, hi in ranges:
            with self.subTest(range=f"[{lo}, {hi}]"):
                self.assertIn((lo, hi), real)

    def test_portal_rejection_cause_is_described(self):
        self.assertIn("Predicted values must be in range [0, 1]", self.exec_sum)
        self.assertIn("DS48-IR-03", self.exec_sum + self.index)


class TestSiteBuildIsReproducible(unittest.TestCase):
    def test_rerunning_the_builder_changes_nothing_but_the_timestamp(self):
        """Pages must be pure functions of the receipts."""
        import subprocess

        script = conftest.repo_path("scripts/build_site_ds48.py")
        if not script.exists():
            self.skipTest("scripts/build_site_ds48.py absent")
        before = {n: (conftest.DOCS / n).read_text() for n in PAGES}
        r = subprocess.run(
            ["python3", str(script)],
            cwd=str(conftest.repo_path(".")), capture_output=True, text=True,
        )
        self.assertEqual(r.returncode, 0, r.stderr[-2000:])
        for n in PAGES:
            with self.subTest(page=n):
                self.assertEqual(before[n], (conftest.DOCS / n).read_text())


if __name__ == "__main__":
    unittest.main()
